-- MySQL Script generated by MySQL Workbench
-- Tue Mar  4 10:14:23 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gymSena
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rol` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centroFormacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centroFormacion` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `programaFormacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `programaFormacion` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(15) NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `fkidCentroForm` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_programaFormacion_centroFormacion1`
    FOREIGN KEY (`fkidCentroForm`)
    REFERENCES `centroFormacion` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ficha` VARCHAR(15) NOT NULL,
  `cantApren` TINYINT NULL,
  `estado` VARCHAR(15) NOT NULL,
  `fechaInicioLect` DATE NULL,
  `fechaFinLect` DATE NULL,
  `fkidProgramaForm` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_grupo_programaFormacion1`
    FOREIGN KEY (`fkidProgramaForm`)
    REFERENCES `programaFormacion` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tipoUsuarioGym`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tipoUsuarioGym` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `tipoDoc` CHAR(1) NOT NULL,
  `documento` VARCHAR(20) NOT NULL,
  `fechaNac` DATE NULL,
  `email` VARCHAR(80) NOT NULL,
  `genero` CHAR(1) NOT NULL,
  `estado` VARCHAR(15) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `eps` VARCHAR(20) NULL,
  `tipoSangre` CHAR(3) NULL,
  `peso` DECIMAL NULL,
  `estatura` DECIMAL NULL,
  `telefonoEmergencia` VARCHAR(15) NULL,
  `password` VARCHAR(255) NULL,
  `obsevaciones` TEXT NULL,
  `fkidRol` INT UNSIGNED NOT NULL,
  `fkidGrupo` INT UNSIGNED NULL,
  `fkidCentroForm` INT UNSIGNED NULL,
  `fkidTipoUserGym` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_usuario_rol`
    FOREIGN KEY (`fkidRol`)
    REFERENCES `rol` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuario_grupo1`
    FOREIGN KEY (`fkidGrupo`)
    REFERENCES `grupo` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuario_centroFormacion1`
    FOREIGN KEY (`fkidCentroForm`)
    REFERENCES `centroFormacion` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuario_tipoUsuarioGym1`
    FOREIGN KEY (`fkidTipoUserGym`)
    REFERENCES `tipoUsuarioGym` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `actividad` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `registroIngreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `registroIngreso` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fechaIn` DATETIME NOT NULL,
  `fechaOut` DATETIME NULL,
  `fkidUserGym` INT UNSIGNED NULL,
  `fkidActividad` INT UNSIGNED NULL,
  `fkidTrainer` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_registroIngreso_actividad1`
    FOREIGN KEY (`fkidActividad`)
    REFERENCES `actividad` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_registroIngreso_usuario1`
    FOREIGN KEY (`fkidTrainer`)
    REFERENCES `usuario` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_registroIngreso_usuario2`
    FOREIGN KEY (`fkidUserGym`)
    REFERENCES `usuario` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlProgreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlProgreso` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fechaRealizacion` DATE NOT NULL,
  `peso` DECIMAL NULL,
  `estatura` DECIMAL NULL,
  `cintura` DECIMAL NULL,
  `cadera` DECIMAL NULL,
  `musloDer` DECIMAL NULL,
  `musloIzq` DECIMAL NULL,
  `brazoDer` DECIMAL NULL,
  `brazoIzq` DECIMAL NULL,
  `antebrazoDer` DECIMAL NULL,
  `antebrazoIzq` DECIMAL NULL,
  `pantorrillaDer` DECIMAL NULL,
  `pantorrillaIzq` DECIMAL NULL,
  `examenMedico` VARCHAR(255) NULL,
  `observaciones` TEXT NULL,
  `fechaExamen` DATE NULL,
  `fkidUsuario` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_controlProgreso_usuario1`
    FOREIGN KEY (`fkidUsuario`)
    REFERENCES `usuario` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
